#!/usr/bin/env bash

#automatically clear dd()'s output and re-run `tail -f` on it.
# [ see: http://api.lullabot.com/dd ]

if [[ $1 = '-h' || $1 = '--help' ]];then
    echo "
    Automatically empty and re-\`tail -f\` your [log_file], being careful about
    file ownership.

    Usage: $(basename $0) [log_file]
    " >&2
    exit 1
fi

# default values
def_file="/tmp/drupal_debug.txt"
def_uid="33" #uid for www-data

# set values
(( $# )) || echo "... no params defaulting to: ${def_file}"
file=${1:-$def_file} #default param
file_uid=$(stat -c %u ${file} 2>/dev/null)
(( $file_uid )) || unset file_uid #avoid root owned file
uid=${file_uid:-$def_uid}

# actual actions
echo "... using owner uid: ${uid}" #debug info
file ${file} >&/dev/null && sudo rm -v ${file} #empty out _existing_ file
sudo -u#${uid} touch ${file} && tail -f ${file}

