#!/usr/bin/env bash

#quick launch for http://dgo.to/, incase the URI isn't easy enough

param="$1"
search="${*}"
if [[ ${param:0:1} == "-" ]];then
    key="$(echo $param | sed -e 's/.//')/"
    search="${@:2}"
else
    key='' #default search projects
fi
${BROWSER:-echo} "http://dgo.to/${key}${search}"
