#!/usr/bin/env bash

# jump you to your current stable or edge code-base.

#@TODO: look at the TODO in PROJECT_BASE declaration -- PROJECT_BASE needs
# to be dynamic, because of utilities like this function.


#@TODO: sub-shell hell prevents this from being a script. set up a standard
# functions-only file to be run at starup (eg.: `libdrupalsh`).
repo=$PROJECT_BASE
if [[ $1 = 'edge' ]];then
    repo=$PROJECT_EDGE
    shift
    cd "$repo/${@}"
else
    cd "$repo"
fi
