#!/bin/bash -x
  #!/usr/bin/env bash

#@TODO: GO BACK TO STRINGS - NOT ARRAYS

#
# easy "project" searching; wrapping `grep` with my PROJECT_BASE vars.

#@TODO: remove this crap from all scripts!
[[ -r ~/bin/lib/libbzsh ]] && source ~/bin/lib/libbzsh || exit 109
OPT_DB=1
OPT_VB=1

####################################################################################

usage() {
    printf "
synopsis:
    \`find\` code and stuff. wrapper to run grep on the usual code base.\n
usage: %s -[m] [grep opts] [-e] search_terms [grep params]
    parameters:
        search_terms is a string you would like to find
    optional:
        -e used to indicate multiple search_terms [see grep (1) ]
        --massive run grep on all of PROJECT_BASE
        -n clean-run: check for env vars that will be used and exit.
         (NOTE: This option only works when no other params are passed).
        \`grep\` is run, by default on CB environment parameter.
" $(basename $0) >&2
    exit 2
}

#sanity check:
if (( $# < 1 ));then
    err 'not enough parameters.'
    usage
elif [[ $1 = '-h' || $1 = '--help' ]]; then
    usage
fi

####################################################################################

# for now, PROJECT_BASE is a safe bet:
if [[ -n $PROJECT_BASE ]];then
    dbg 'found one of your env. vars'
    if [[ -n $CB && $1 != "--massive" ]];then
        dbg 'setting "${CB[@]}" search param'
        BASE=("${CB[@]}")
    else
        dbg 'setting "massive" search param'
        BASE=("${PROJECT_BASE}")
        shift #@TODO: why am i doing this?
    fi
else
    dbg 'found NO env vars (CB or PROJECT_BASE).'
fi

#act as an even thinner direct wrapper to grep
if [[ -z $BASE && if_debug ]] ;then
        warn "no 'code base' env vars found..
assuming you provided the files to search, see grep(1)."
fi

check_env() {
    dbg "testing if PROJECT_BASE (project codebase) has been set:"
    if_debug && declare -p PROJECT_BASE

    dbg "testing if CB (main codebase) has been set:"
    if_debug && declare -p CB

    dbg "testing if BASE has been decided:"
    if_debug && declare -p BASE
}

if (( $# == 1 )) && [[ $1 = '-n' ]]; then
    opt_db=1
    check_env
    exit 0
fi

#grep "$@" $PROJECT_BASE/sites/all/{modules/{features,custom},themes/zagat}
dbg "running the below:\n\tgrep ${@} ${BASE[@]}"
grep $@ ${BASE[@]}

