#!/usr/bin/env bash

#toggle `module_name` module on and off

if [[ -z ${1//-*/} ]];then
    if [[ $1 = '-h' || $1 = '--help' ]];then
        printf "
Synopsis: toggle drupal [module] on/off.

Usage: %s -c [module]
    -c  Just run a _check_ if the given module is on/off.\n"\
                $(basename $0) >&2
        exit 1
    fi

    o=${1/-/}; shift
    case ${o} in
        c):
            #only _CHECK_ if our module is on
            opt_check=1
            ;;
        *):
            echo "error: '${o}' is not a valid flag." >&2
            exit 1
            ;;
    esac
fi

#set the module name
n=${1:-devel_themer}

#run "check only" option
if (( opt_check ));then
    drush pm-list 2>/dev/null | grep -i "${n}"

    if (( $? )); then
        printf "error: seems like you don't have %s module in your codebase.\n" \
            ${n} >&2
        exit 1
    fi

    exit 0
fi

#run normally
[[ $(drush pm-list | grep ${n} | grep 'Enabled') ]] && drush -y dis ${n} || drush -y en ${n}

